apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: hellojsapp
  name: hellojsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellojsapp  
  template:
    metadata:      
      labels:
        app: hellojsapp
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/cloud-native-project-spoke/cloud-native-repo/hellojsapp:v1.0
        name: hellojsapp
        resources:
          requests:
            cpu: "0.25m"
            memory: "250Mi"
          limits:
            cpu: "0.5m"
            memory: "500Mi"
        ports:
          - containerPort: 7071
